In [2]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
class LinearRegression:
    def __init__(self) -> None:
        self.w = np.array([])

    def fit(self, X_train, y_train):
        n = X_train.shape[0]

        X = np.hstack((np.ones((n, 1)), X_train))
        y = y_train

        self.w = np.linalg.inv(X.T @ X) @ X.T @ y

    def predict(self, X_test):
        n = X_test.shape[0]

        X = np.hstack((np.ones((n, 1)), X_test))
        return X @ self.w

    @property
    def _coef(self):
        return self.w[1:]

    @property
    def _intercept(self):
        return self.w[0]

In [4]:
X, y = load_diabetes(return_X_y=True)

In [5]:
X[:2], y[:2]

(array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
         -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
         -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405]]),
 array([151.,  75.]))

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=99
)

In [7]:
lr = LinearRegression()

In [8]:
lr.fit(X_train, y_train)

In [9]:
lr._coef, lr._intercept

(array([  47.66758099, -293.52801765,  529.78140846,  339.68784283,
        -759.24057527,  392.21681079,   67.2075408 ,  206.59808397,
         712.24879014,   70.69051114]),
 np.float64(155.34268085302142))

In [10]:
r2_score(y_test, lr.predict(X_test))

0.43268345187633117